Reformat energy model interface (#112)
* Reformat energy model interface

* update dpa2 example

* Copy and fix typos in branch 'refact-se-uni'

* try to fix jit compilation error

known issue: "RuntimeError: Unsupported value kind: Tensor"

* fix bug: slurm on local size

* Revert "try to fix jit compilation error"

This reverts commit 9a69f6c4056202e48af288e3801a9ad56d2ac2e2.

* Fix jit in se_uni

* Fix jit in DPA-2; upload infer; fix UTs

* Update KFWrapper.py

* Update training.py

* Update test_embedding_net.py

* Update test_fitting_net.py

* Update test_fitting_net.py

* Update test_fitting_net.py

* Update test_loss.py

* Update test_loss.py

* Update test_model.py

* Update test_model.py

* Update test_nlist.py

* Update test_nlist.py

* Update test_nlist.py

* Update nlist.py

* Update nlist.py

* Update test_nlist.py

* fix uts

* Update test_unused_params.py

* Update test_unused_params.py

* try to fix ut

* add ut for atomic virial

* Update test_model.py

* Update test_model.py

* Update ener.py

* Update test_model.py

* correct atomic virial. add option to swith it on or off

* fix bug in model test

* mv the key of do_atomic_virial to forward and forward_lower

* fix ut of unused params

* Add uts for jit and training

Add uts for jit and training
Add option to disable tqdm

* Update ci-test.yml

* deepcopy global dict

Signed-off-by: Jinzhe Zeng <jinzhe.zeng@rutgers.edu>

* Temporaryly change the ut machine

* Revert "Temporaryly change the ut machine"

This reverts commit 741fa2742b5fa268914881edcbf438ebe63aaf5f.

* try to slim the ut

* try to slim ut

* revert 'slim ut'

* clean up comments

* revert indent in uts

* Revert "revert indent in uts"

This reverts commit 11085e44ace2943073b2f3ee3c159404d966e0e9.

* revert indent in uts

---------

Signed-off-by: Jinzhe Zeng <jinzhe.zeng@rutgers.edu>
Co-authored-by: caic99 <amoycaic@gmail.com>
Co-authored-by: zxysbsbzxy <UCASzxy@outlook.com>
Co-authored-by: Han Wang <wang_han@iapcm.ac.cn>
Co-authored-by: Jinzhe Zeng <jinzhe.zeng@rutgers.edu>